"""sprint3: remitentes y metadatos

Revision ID: 03fc2c929cb4
Revises: dae196e1564e
Create Date: 2026-03-24 20:35:49.736862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fc2c929cb4'
down_revision: Union[str, None] = 'dae196e1564e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
