"""sprint5: log_auditoria

Revision ID: 27dd301f144f
Revises: f9abbf6f1982
Create Date: 2026-03-24 20:38:28.146792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27dd301f144f'
down_revision: Union[str, None] = 'f9abbf6f1982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
