"""sprint1: entidad, dependencias, canales, catalogos, configuracion

Revision ID: c71ba4b5cb25
Revises: 1c5f6fe96192
Create Date: 2026-03-23 19:08:17.555607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71ba4b5cb25'
down_revision: Union[str, None] = '1c5f6fe96192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('config_email', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canales_id'), 'canales', ['id'], unique=False)
    op.create_table('configuracion_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefijo_radicado', sa.String(length=10), nullable=False),
    sa.Column('anio_radicado', sa.Integer(), nullable=False),
    sa.Column('secuencia_actual', sa.Integer(), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=500), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=True),
    sa.Column('sistema_listo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_sistema_id'), 'configuracion_sistema', ['id'], unique=False)
    op.create_table('dependencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencias_id'), 'dependencias', ['id'], unique=False)
    op.create_table('entidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email_institucional', sa.String(length=100), nullable=True),
    sa.Column('configurada', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entidad_id'), 'entidad', ['id'], unique=False)
    op.create_table('plazos_respuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dias_habiles', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plazos_respuesta_id'), 'plazos_respuesta', ['id'], unique=False)
    op.create_table('tipos_requerimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_requerimiento_id'), 'tipos_requerimiento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_requerimiento_id'), table_name='tipos_requerimiento')
    op.drop_table('tipos_requerimiento')
    op.drop_index(op.f('ix_plazos_respuesta_id'), table_name='plazos_respuesta')
    op.drop_table('plazos_respuesta')
    op.drop_index(op.f('ix_entidad_id'), table_name='entidad')
    op.drop_table('entidad')
    op.drop_index(op.f('ix_dependencias_id'), table_name='dependencias')
    op.drop_table('dependencias')
    op.drop_index(op.f('ix_configuracion_sistema_id'), table_name='configuracion_sistema')
    op.drop_table('configuracion_sistema')
    op.drop_index(op.f('ix_canales_id'), table_name='canales')
    op.drop_table('canales')
    # ### end Alembic commands ###
