"""HU01_auditoria_acuse_politica_privacidad

Revision ID: d0e596424db4
Revises: 27dd301f144f
Create Date: 2026-04-05 09:23:11.179885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e596424db4'
down_revision: Union[str, None] = '27dd301f144f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_nombre', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_auditoria_id'), 'bitacora_auditoria', ['id'], unique=False)
    # server_default='false' rellena las filas existentes antes de aplicar NOT NULL
    op.add_column('canales', sa.Column('acuse_configurado', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('configuracion_sistema', sa.Column('politica_privacidad_activa', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('configuracion_sistema', sa.Column('politica_privacidad_texto', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_sistema', 'politica_privacidad_texto')
    op.drop_column('configuracion_sistema', 'politica_privacidad_activa')
    op.drop_column('canales', 'acuse_configurado')
    op.drop_index(op.f('ix_bitacora_auditoria_id'), table_name='bitacora_auditoria')
    op.drop_table('bitacora_auditoria')
    # ### end Alembic commands ###
