"""sprint2: recepciones y adjuntos

Revision ID: dae196e1564e
Revises: c71ba4b5cb25
Create Date: 2026-03-24 20:30:22.756543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae196e1564e'
down_revision: Union[str, None] = 'c71ba4b5cb25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remitentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_persona', sa.String(length=20), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('tipo_identificacion', sa.String(length=30), nullable=True),
    sa.Column('numero_identificacion', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remitentes_email'), 'remitentes', ['email'], unique=False)
    op.create_index(op.f('ix_remitentes_id'), 'remitentes', ['id'], unique=False)
    op.create_index(op.f('ix_remitentes_numero_identificacion'), 'remitentes', ['numero_identificacion'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_accion'), 'log_auditoria', ['accion'], unique=False)
    op.create_index(op.f('ix_log_auditoria_created_at'), 'log_auditoria', ['created_at'], unique=False)
    op.create_index(op.f('ix_log_auditoria_id'), 'log_auditoria', ['id'], unique=False)
    op.create_table('recepciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal_id', sa.Integer(), nullable=False),
    sa.Column('asunto_provisional', sa.String(length=300), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('recibido_por_id', sa.Integer(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canal_id'], ['canales.id'], ),
    sa.ForeignKeyConstraint(['recibido_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recepciones_id'), 'recepciones', ['id'], unique=False)
    op.create_table('adjuntos_recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('nombre_original', sa.String(length=300), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=300), nullable=False),
    sa.Column('ruta', sa.String(length=500), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjuntos_recepcion_id'), 'adjuntos_recepcion', ['id'], unique=False)
    op.create_table('metadatos_recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=300), nullable=False),
    sa.Column('tipo_soporte', sa.String(length=30), nullable=False),
    sa.Column('numero_anexos', sa.Integer(), nullable=True),
    sa.Column('tipo_requerimiento_id', sa.Integer(), nullable=True),
    sa.Column('plazo_respuesta_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('numero_referencia', sa.String(length=100), nullable=True),
    sa.Column('fecha_documento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plazo_respuesta_id'], ['plazos_respuesta.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepciones.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['remitentes.id'], ),
    sa.ForeignKeyConstraint(['tipo_requerimiento_id'], ['tipos_requerimiento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recepcion_id')
    )
    op.create_index(op.f('ix_metadatos_recepcion_id'), 'metadatos_recepcion', ['id'], unique=False)
    op.create_table('radicados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_radicado', sa.String(length=30), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('dependencia_id', sa.Integer(), nullable=False),
    sa.Column('radicado_por_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('ruta_constancia', sa.String(length=500), nullable=True),
    sa.Column('fecha_radicacion', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dependencia_id'], ['dependencias.id'], ),
    sa.ForeignKeyConstraint(['radicado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recepcion_id')
    )
    op.create_index(op.f('ix_radicados_id'), 'radicados', ['id'], unique=False)
    op.create_index(op.f('ix_radicados_numero_radicado'), 'radicados', ['numero_radicado'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radicados_numero_radicado'), table_name='radicados')
    op.drop_index(op.f('ix_radicados_id'), table_name='radicados')
    op.drop_table('radicados')
    op.drop_index(op.f('ix_metadatos_recepcion_id'), table_name='metadatos_recepcion')
    op.drop_table('metadatos_recepcion')
    op.drop_index(op.f('ix_adjuntos_recepcion_id'), table_name='adjuntos_recepcion')
    op.drop_table('adjuntos_recepcion')
    op.drop_index(op.f('ix_recepciones_id'), table_name='recepciones')
    op.drop_table('recepciones')
    op.drop_index(op.f('ix_log_auditoria_id'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_created_at'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_accion'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_remitentes_numero_identificacion'), table_name='remitentes')
    op.drop_index(op.f('ix_remitentes_id'), table_name='remitentes')
    op.drop_index(op.f('ix_remitentes_email'), table_name='remitentes')
    op.drop_table('remitentes')
    # ### end Alembic commands ###
